### ISSUE TITLE
Cannot build (Unexpected token import)

### ISSUE THREAD

**Issue by awagner-mainz** [TEIC/CETEIcean#7]
[npm-debug.log.txt](https://github.com/TEIC/CETEIcean/files/413057/npm-debug.log.txt)

Hi,
My build fails:

```
c:\Users\andrewag\github\CETEIcean>npm run build
> CETEIcean@0.0.0 build c:\Users\andrewag\github\CETEIcean
> rollup -c rollup.config.js
Unexpected token import
C:\Users\andrewag\github\CETEIcean\rollup.config.js:1
(function (exports, require, module, __filename, __dirname) { import babel from 'rollup-plugin-babel';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions..js (C:\Users\andrewag\github\CETEIcean\node_modules\rollup\bin\runRollup.js:56:6)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at C:\Users\andrewag\github\CETEIcean\node_modules\rollup\bin\runRollup.js:61:19
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! CETEIcean@0.0.0 build: `rollup -c rollup.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the CETEIcean@0.0.0 build script 'rollup -c rollup.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the CETEIcean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rollup -c rollup.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs CETEIcean
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls CETEIcean
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\andrewag\github\CETEIcean\npm-debug.log
```

From googling I got the impression that this has to do with babel/ES/node versions, but I understand nothing of this. I have just cloned CETEIcean and downloaded the current node.js, but it's all on windows at the moment. During `npm i` I did get this:

```
c:\Users\andrewag\github\CETEIcean>npm i
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
> spawn-sync@1.0.15 postinstall c:\Users\andrewag\github\CETEIcean\node_modules\spawn-sync
> node postinstall
CETEIcean@0.0.0 c:\Users\andrewag\github\CETEIcean
+-- babel-preset-es2015@6.13.2
| +-- babel-plugin-check-es2015-constants@6.8.0
| | `-- babel-runtime@6.11.6
| |   +-- core-js@2.4.1
| |   `-- regenerator-runtime@0.9.5
| +-- babel-plugin-transform-es2015-arrow-functions@6.8.0
| +-- babel-plugin-transform-es2015-block-scoped-functions@6.8.0
| +-- babel-plugin-transform-es2015-block-scoping@6.10.1
| | +-- babel-template@6.9.0
| | +-- babel-traverse@6.13.0
| | | +-- globals@8.18.0
| | | `-- invariant@2.2.1
| | |   `-- loose-envify@1.2.0
| | |     `-- js-tokens@1.0.3
| | +-- babel-types@6.13.0
| | | +-- esutils@2.0.2
| | | `-- to-fast-properties@1.0.2
| | `-- lodash@4.14.2
| +-- babel-plugin-transform-es2015-classes@6.9.0
| | +-- babel-helper-define-map@6.9.0
| | +-- babel-helper-function-name@6.8.0
| | +-- babel-helper-optimise-call-expression@6.8.0
| | +-- babel-helper-replace-supers@6.8.0
| | `-- babel-messages@6.8.0
| +-- babel-plugin-transform-es2015-computed-properties@6.8.0
| +-- babel-plugin-transform-es2015-destructuring@6.9.0
| +-- babel-plugin-transform-es2015-duplicate-keys@6.8.0
| +-- babel-plugin-transform-es2015-for-of@6.8.0
| +-- babel-plugin-transform-es2015-function-name@6.9.0
| +-- babel-plugin-transform-es2015-literals@6.8.0
| +-- babel-plugin-transform-es2015-modules-amd@6.8.0
| +-- babel-plugin-transform-es2015-modules-commonjs@6.11.5
| | `-- babel-plugin-transform-strict-mode@6.11.3
| +-- babel-plugin-transform-es2015-modules-systemjs@6.12.0
| | `-- babel-helper-hoist-variables@6.8.0
| +-- babel-plugin-transform-es2015-modules-umd@6.12.0
| +-- babel-plugin-transform-es2015-object-super@6.8.0
| +-- babel-plugin-transform-es2015-parameters@6.11.4
| | +-- babel-helper-call-delegate@6.8.0
| | `-- babel-helper-get-function-arity@6.8.0
| +-- babel-plugin-transform-es2015-shorthand-properties@6.8.0
| +-- babel-plugin-transform-es2015-spread@6.8.0
| +-- babel-plugin-transform-es2015-sticky-regex@6.8.0
| | `-- babel-helper-regex@6.9.0
| +-- babel-plugin-transform-es2015-template-literals@6.8.0
| +-- babel-plugin-transform-es2015-typeof-symbol@6.8.0
| +-- babel-plugin-transform-es2015-unicode-regex@6.11.0
| | `-- regexpu-core@2.0.0
| |   +-- regenerate@1.3.1
| |   +-- regjsgen@0.2.0
| |   `-- regjsparser@0.1.5
| |     `-- jsesc@0.5.0
| `-- babel-plugin-transform-regenerator@6.11.4
|   +-- babel-plugin-syntax-async-functions@6.13.0
|   +-- babylon@6.8.4
|   `-- private@0.1.6
+-- babel-preset-es2015-rollup@1.1.0
| +-- babel-plugin-external-helpers@6.8.0
| `-- modify-babel-preset@1.2.0
|   `-- require-relative@0.8.7
+-- http-server@0.9.0
| +-- colors@1.0.3
| +-- corser@2.0.0
| +-- ecstatic@1.4.1
| | +-- he@0.5.0
| | +-- mime@1.3.4
| | `-- url-join@1.1.0
| +-- http-proxy@1.14.0
| | +-- eventemitter3@1.2.0
| | `-- requires-port@1.0.0
| +-- opener@1.4.1
| +-- optimist@0.6.1
| | +-- minimist@0.0.10
| | `-- wordwrap@0.0.3
| +-- portfinder@0.4.0
| | +-- async@0.9.0
| | `-- mkdirp@0.5.1
| |   `-- minimist@0.0.8
| `-- union@0.4.4
|   `-- qs@2.3.3
+-- onchange@2.4.0
| +-- arrify@1.0.1
| +-- chokidar@1.4.3
| | +-- anymatch@1.3.0
| | | `-- micromatch@2.3.11
| | |   +-- arr-diff@2.0.0
| | |   | `-- arr-flatten@1.0.1
| | |   +-- array-unique@0.2.1
| | |   +-- braces@1.8.5
| | |   | +-- expand-range@1.8.2
| | |   | | `-- fill-range@2.2.3
| | |   | |   +-- is-number@2.1.0
| | |   | |   +-- isobject@2.1.0
| | |   | |   `-- randomatic@1.1.5
| | |   | +-- preserve@0.2.0
| | |   | `-- repeat-element@1.1.2
| | |   +-- expand-brackets@0.1.5
| | |   | `-- is-posix-bracket@0.1.1
| | |   +-- extglob@0.3.2
| | |   +-- filename-regex@2.0.0
| | |   +-- kind-of@3.0.4
| | |   | `-- is-buffer@1.1.4
| | |   +-- normalize-path@2.0.1
| | |   +-- object.omit@2.0.0
| | |   | +-- for-own@0.1.4
| | |   | | `-- for-in@0.1.5
| | |   | `-- is-extendable@0.1.1
| | |   +-- parse-glob@3.0.4
| | |   | +-- glob-base@0.3.0
| | |   | `-- is-dotfile@1.0.2
| | |   `-- regex-cache@0.4.3
| | |     +-- is-equal-shallow@0.1.3
| | |     `-- is-primitive@2.0.0
| | +-- async-each@1.0.0
| | +-- glob-parent@2.0.0
| | +-- inherits@2.0.1
| | +-- is-binary-path@1.0.1
| | | `-- binary-extensions@1.5.0
| | +-- is-glob@2.0.1
| | | `-- is-extglob@1.0.0
| | +-- path-is-absolute@1.0.0
| | `-- readdirp@2.1.0
| |   +-- graceful-fs@4.1.5
| |   +-- readable-stream@2.1.4
| |   | +-- buffer-shims@1.0.0
| |   | +-- core-util-is@1.0.2
| |   | +-- isarray@1.0.0
| |   | +-- process-nextick-args@1.0.7
| |   | +-- string_decoder@0.10.31
| |   | `-- util-deprecate@1.0.2
| |   `-- set-immediate-shim@1.0.1
| +-- cross-spawn@2.1.5
| | +-- cross-spawn-async@2.2.4
| | | +-- lru-cache@4.0.1
| | | | +-- pseudomap@1.0.2
| | | | `-- yallist@2.0.0
| | | `-- which@1.2.10
| | |   `-- isexe@1.1.2
| | `-- spawn-sync@1.0.15
| |   +-- concat-stream@1.5.1
| |   | +-- readable-stream@2.0.6
| |   | `-- typedarray@0.0.6
| |   `-- os-shim@0.1.3
| `-- minimist@1.2.0
+-- rollup@0.26.2
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.0.0
| | +-- strip-ansi@3.0.1
| | `-- supports-color@2.0.0
| `-- source-map-support@0.4.2
|   `-- source-map@0.1.32
|     `-- amdefine@1.0.0
+-- rollup-plugin-babel@2.4.0
| +-- babel-core@6.13.2
| | +-- babel-code-frame@6.11.0
| | | `-- js-tokens@2.0.0
| | +-- babel-generator@6.11.4
| | | `-- detect-indent@3.0.1
| | |   +-- get-stdin@4.0.1
| | |   `-- repeating@1.1.3
| | |     `-- is-finite@1.0.1
| | |       `-- number-is-nan@1.0.0
| | +-- babel-helpers@6.8.0
| | +-- babel-register@6.11.6
| | | +-- home-or-tmp@1.0.0
| | | | +-- os-tmpdir@1.0.1
| | | | `-- user-home@1.1.1
| | | `-- source-map-support@0.2.10
| | |   `-- source-map@0.1.32
| | +-- convert-source-map@1.3.0
| | +-- debug@2.2.0
| | | `-- ms@0.7.1
| | +-- json5@0.4.0
| | +-- minimatch@3.0.3
| | | `-- brace-expansion@1.1.6
| | |   +-- balanced-match@0.4.2
| | |   `-- concat-map@0.0.1
| | +-- path-exists@1.0.0
| | +-- shebang-regex@1.0.0
| | +-- slash@1.0.0
| | `-- source-map@0.5.6
| +-- object-assign@4.1.0
| `-- rollup-pluginutils@1.5.1
|   `-- estree-walker@0.2.1
`-- rollup-plugin-uglify@1.0.0
  `-- uglify-js@2.7.0
    +-- async@0.2.10
    +-- uglify-to-browserify@1.0.2
    `-- yargs@3.10.0
      +-- camelcase@1.2.1
      +-- cliui@2.1.0
      | +-- center-align@0.1.3
      | | +-- align-text@0.1.4
      | | | +-- longest@1.0.1
      | | | `-- repeat-string@1.5.4
      | | `-- lazy-cache@1.0.4
      | +-- right-align@0.1.3
      | `-- wordwrap@0.0.2
      +-- decamelize@1.2.0
      `-- window-size@0.1.0
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14`
```

Thanks for any help

**Comment by hcayless** [comment]
I haven't tried this at all on Windows, but yes, that look like it simply isn't understanding the ES6 syntax of the rollup config file, which means Babel isn't working. I'll have to set up a VM to try to troubleshoot this, but in the meantime if you just want to play around with it, you can grab the compiled JS file from the latest release and just use it like a regular Javascript library. The dev environment gives you a nice embedded web server to work with and rebuilds your sources when they change, but that's just a convenience really.

**Comment by awagner-mainz** [comment]
Just a quick update: when I globally installed rollup and ran `rollup -c` in the project directory, it went okay and produced the dist/CETEI.js, only the `npm run build` step would not work. No idea why, but anyway I can play around with it now. Thanks so far
